# Generated by Django 4.0.5 on 2022-06-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ManyToManyField(help_text='Idioma de la instancia del libro', to='catalog.language'),
        ),
    ]
