# Generated by Django 4.0.5 on 2022-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
