# Generated by Django 4.0.5 on 2022-06-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification',
            field=models.BigIntegerField(unique=True),
        ),
    ]
