# Generated by Django 4.0.5 on 2022-07-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_snippet_category_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
